# Generated by Django 5.1.4 on 2025-01-20 17:44

import main_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main_app.models.recipe_image_directory_path),
        ),
    ]
